2018-11-01 15:15:37,026:INFO: * Restarting with stat
2018-11-01 15:15:40,222:WARNING: * Debugger is active!
2018-11-01 15:15:40,226:INFO: * Debugger PIN: 736-574-432
2018-11-01 15:15:40,234:INFO: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-11-01 15:15:41,826:INFO:In the Index Page...........
2018-11-01 15:15:41,826:INFO:Twitter Zip is not Found in the Directory..
2018-11-01 15:15:41,827:INFO:InstaGram Zip is not Found in the Directory..
2018-11-01 15:15:41,827:INFO:Google Plus Zip file Removed Successfully..
2018-11-01 15:15:41,838:INFO:127.0.0.1 - - [01/Nov/2018 15:15:41] "GET / HTTP/1.1" 200 -
2018-11-01 15:15:44,600:INFO:In the Clear Credentials Function........
2018-11-01 15:15:44,601:INFO:Checking for credentials in the Session...
2018-11-01 15:15:44,601:INFO:Redirecting the Control to the Home Page with the print_index_table function..
2018-11-01 15:15:44,601:INFO:In the Print_Index_Table Function..
2018-11-01 15:15:44,601:INFO:Redirecting to the Home Page......
2018-11-01 15:15:44,602:INFO:127.0.0.1 - - [01/Nov/2018 15:15:44] "GET /clear HTTP/1.1" 200 -
2018-11-01 15:15:46,215:INFO:In the Google_Plus Section.......
2018-11-01 15:15:46,215:INFO:Redirecting the Control to the Google Plus Authorize Section...
2018-11-01 15:15:46,215:INFO:127.0.0.1 - - [01/Nov/2018 15:15:46] "GET /google_plus HTTP/1.1" 302 -
2018-11-01 15:15:46,227:INFO:In the Authorize Section of the Google Plus...
2018-11-01 15:15:46,227:INFO:Getting the AUthorization of the Google Plus for the Validation...
2018-11-01 15:15:46,228:INFO:Getting the Redirect_Uri of the Google Plus.......
2018-11-01 15:15:46,229:INFO:Getting the Authorization_url of the Google Plus....
2018-11-01 15:15:46,230:INFO:Inserting the State of the Google Plus in the Session...
2018-11-01 15:15:46,230:INFO:Redirecting the Function...
2018-11-01 15:15:46,414:INFO:127.0.0.1 - - [01/Nov/2018 15:15:46] "GET /authorize HTTP/1.1" 302 -
2018-11-01 15:15:58,408:INFO:In the Oauth2Callback Function...
2018-11-01 15:15:58,408:INFO:Getting the State from the Session..
2018-11-01 15:15:58,408:INFO:Getting the Authorization from the oauth2callback....
2018-11-01 15:15:58,408:INFO:Getting the Redirect Uri from the Google OauthCallBack...
2018-11-01 15:15:58,408:INFO:Get the Authorization Response of the Google Plus....
2018-11-01 15:15:58,413:INFO:Get the Access Token of the Google Plus...
2018-11-01 15:15:58,944:INFO:Get the Credentials of the Google Plus...
2018-11-01 15:15:58,946:INFO:Storing the Crdentials of the Google Plus in the Session... 
2018-11-01 15:15:58,947:INFO:In the Credentials_to_Dictionary Function...
2018-11-01 15:15:58,948:INFO:Redirecting the Function to the Test_API_Request..
2018-11-01 15:15:59,192:INFO:127.0.0.1 - - [01/Nov/2018 15:15:59] "GET /oauth2callback?state=uLBjZxCbN02lfHm8gJzDNMDLp79Kx2&code=4%2FiADInlAsEQm1frqsPa1YqnliMPUi5zD70GE3bo7Y775XiO5ty792cKyfQs4P6yKlQ0wDj5e5gZSX5QFBB1hFSYE&scope=openid+email+profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.me+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.profile.agerange.read+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.stream.write+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.profile.language.read+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.metadata.readonly HTTP/1.1" 302 -
2018-11-01 15:15:59,233:INFO:In the Google_Plus Section.......
2018-11-01 15:15:59,233:INFO:Check for the Google Plus Credentials and Get it from the Session...
2018-11-01 15:15:59,234:INFO:Building and Creating the Data of Google Plus...
2018-11-01 15:15:59,260:WARNING:file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "C:\Users\Ritesh\PycharmProjects\Flask\venv\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ritesh\PycharmProjects\Flask\venv\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ritesh\PycharmProjects\Flask\venv\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Ritesh\PycharmProjects\Flask\venv\lib\site-packages\googleapiclient\discovery_cache\__init__.py", line 41, in autodetect
    from . import file_cache
  File "C:\Users\Ritesh\PycharmProjects\Flask\venv\lib\site-packages\googleapiclient\discovery_cache\file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
2018-11-01 15:15:59,260:INFO:URL being requested: GET https://www.googleapis.com/discovery/v1/apis/plus/v1/rest
2018-11-01 15:16:00,198:INFO:Getting the people Data from the Google Plus....
2018-11-01 15:16:00,202:INFO:URL being requested: GET https://www.googleapis.com/plus/v1/people/me?alt=json
2018-11-01 15:16:00,912:INFO:Getting the All the Data of Google Plus...........
2018-11-01 15:16:00,922:INFO:URL being requested: GET https://www.googleapis.com/plus/v1/people/me/activities/public?alt=json
2018-11-01 15:16:00,922:INFO:Executing the Request and ready for Data Retrieval.......
2018-11-01 15:16:01,546:INFO:Creation of Google Plus DataFrame..........
2018-11-01 15:16:01,551:INFO:Google Plus DataFrame Created Successfully..
2018-11-01 15:16:01,552:INFO:Getting the Image_url from the Google Plus Data....
2018-11-01 15:16:01,552:INFO:Image_Url is Empty........
2018-11-01 15:16:01,553:INFO:Getting the Image_link from the Google Plus Data....
2018-11-01 15:16:01,553:INFO:Image_Link is Empty......
2018-11-01 15:16:01,554:INFO:Getting the Image_url from the Google Plus Data....
2018-11-01 15:16:01,554:INFO:Image_Url is Empty........
2018-11-01 15:16:01,555:INFO:Getting the Image_link from the Google Plus Data....
2018-11-01 15:16:01,555:INFO:Image_Link is Empty......
2018-11-01 15:16:01,555:INFO:Getting the Image_url from the Google Plus Data....
2018-11-01 15:16:01,555:INFO:Image_Url is Empty........
2018-11-01 15:16:01,555:INFO:Getting the Image_link from the Google Plus Data....
2018-11-01 15:16:01,555:INFO:Image_Link is Empty......
2018-11-01 15:16:01,555:INFO:Getting the Image_url from the Google Plus Data....
2018-11-01 15:16:01,556:INFO:Image_Url is Empty........
2018-11-01 15:16:01,556:INFO:Getting the Image_link from the Google Plus Data....
2018-11-01 15:16:01,556:INFO:Image_Link is Empty......
2018-11-01 15:16:01,558:INFO:Getting the Image_url from the Google Plus Data....
2018-11-01 15:16:01,558:INFO:Image_Url is Empty........
2018-11-01 15:16:01,558:INFO:Getting the Image_link from the Google Plus Data....
2018-11-01 15:16:01,558:INFO:Image_Link is Empty......
2018-11-01 15:16:01,558:INFO:Inserting the Image_Url as the Column in the Google Plus DataFrame...
2018-11-01 15:16:01,559:INFO:Failed to Execute the Google Plus Section....
2018-11-01 15:16:01,744:INFO:127.0.0.1 - - [01/Nov/2018 15:16:01] "GET /google_plus HTTP/1.1" 200 -
2018-11-01 15:16:07,840:INFO:In the Logs Function to get the Logs File for the Debugging...
2018-11-01 15:16:07,877:INFO:Zip file successfully created for Logs Directory....
2018-11-01 15:16:08,141:INFO:127.0.0.1 - - [01/Nov/2018 15:16:08] "GET /logs HTTP/1.1" 200 -
2018-11-01 15:16:39,425:INFO: * Detected change in 'C:\\Users\\Ritesh\\PycharmProjects\\Flask\\venv\\flasknew\\api.py', reloading
2018-11-01 15:16:39,581:INFO: * Restarting with stat
2018-11-01 15:16:42,380:WARNING: * Debugger is active!
2018-11-01 15:16:42,389:INFO: * Debugger PIN: 736-574-432
2018-11-01 15:16:42,398:INFO: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-11-01 15:16:47,338:INFO:In the Index Page...........
2018-11-01 15:16:47,341:INFO:Twitter Zip is not Found in the Directory..
2018-11-01 15:16:47,341:INFO:InstaGram Zip is not Found in the Directory..
2018-11-01 15:16:47,341:INFO:Google Plus Zip is not Found in the Directory..
2018-11-01 15:16:47,355:INFO:127.0.0.1 - - [01/Nov/2018 15:16:47] "GET / HTTP/1.1" 200 -
